TITLE "CYBOLITE ZIPPER"
PROMPT "www.CYBOLITE.com"
@ECHO OFF
CLS
@REM BANNER M-KRS BACKUP-2019

set /p ARC="ENTER ARCHIEVE TYPE (zip/7z): "
set /p SRC="ENTER SOURCE PATH (c / d / e): "
set /p DST="ENTER DESTINATION PATH (c / d / e): "

echo FileType %ARC% Set!
echo SOURCE DRIVE SET TO %SRC%:\
echo DESTINATION DRIVE SET TO %DST%:\

set SRC_PATH=%SRC%:\
set DST_PATH=%DST%:\

7z a -r -tzip %DST_PATH% -mx=9 -ir!%SRC_PATH%\*.CSH -ir!%SRC_PATH%\*.CSH -ir!%SRC_PATH%\*.CSH -ir!%SRC_PATH%\*.CSH -ir!%SRC_PATH%\*.CSH -ir!%SRC_PATH%\*.CSH -ir!DIR7\*.CSH

@REM if exist test3\ (
@REM   echo Yes 
@REM ) else (
@REM   echo No
@REM )

@REM 7z a -tzip archive.zip -ir!DIR1\*.CSH -ir!DIR2\*.BAT -ir!DIR3\*.XLS -ir!DIR4\*.DOC -ir!DIR5\*.TXT -ir!DIR6\*.BLS -ir!DIR7\*.ARJ
@REM 7z a -m -p%PASSWORD% -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on -mmt=on
@REM 7z a -t7z archive.7z *.exe *.dll -mx9
@REM 7z a -r -tzip x:\RAJ\MKBACKUP\D005(23) z:\DATA\D5\*.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
@REM 7z a -tzip archive.zip -ir!.\*.xlsx -ir!.\*.pdf
@REM 7z a -tzip archive.zip -wc:\temp
@REM 7z a -tzip archive.zip -ir!DIR1\*.CSH -ir!DIR2\*.BAT -ir!DIR3\*.XLS -ir!DIR4\*.DOC -ir!DIR5\*.TXT -ir!DIR6\*.BLS -ir!DIR7\*.ARJ

ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D005(23) z:\DATA\D5\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D006(23) z:\DATA\D6\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D007(23) z:\DATA\D7\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D008(23) z:\DATA\D8\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D009(23) z:\DATA\D9\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D010(23) z:\DATA\D10\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D012(23) z:\DATA\D12\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D014(23) z:\DATA\D14\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D019(23) z:\DATA\D19\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D020(23) z:\DATA\D20\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D022(23) z:\DATA\D22\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D024(23) z:\DATA\D24\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D025(23) z:\DATA\D25\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D026(23) z:\DATA\D26\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D027(23) z:\DATA\D27\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D029(23) z:\DATA\D29\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D034(23) z:\DATA\D34\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D036(23) z:\DATA\D36\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D047(23) z:\DATA\D47\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D048(23) z:\DATA\D48\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D050(23) z:\DATA\D50\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D053(23) z:\DATA\D53\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D055(23) z:\DATA\D55\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D061(23) z:\DATA\D61\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D062(23) z:\DATA\D62\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D093(23) z:\DATA\D93\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D094(23) z:\DATA\D94\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D095(23) z:\DATA\D95\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D100(23) z:\DATA\D100\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D101(23) z:\DATA\D101\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D102(23) z:\DATA\D102\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D103(23) z:\DATA\D103\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D104(23) z:\DATA\D104\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D105(23) z:\DATA\D105\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D106(23) z:\DATA\D106\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D107(23) z:\DATA\D107\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D112(23) z:\DATA\D112\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D114(23) z:\DATA\D114\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D115(23) z:\DATA\D115\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\D122(23) z:\DATA\D122\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\CAL-(23) z:\DATA\CAL\ AM22*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\CAL-(23) z:\DATA\CAL\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\CHU-(23) z:\DATA\CHURU\ AM22*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\CHU-(23) z:\DATA\CHURU\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\SHAR(23) z:\DATA\SHARE\ *.DBF
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\SONU(23) z:\DATA\SONU\ AM22*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\SONU(23) z:\DATA\SONU\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\RGH-(23) z:\DATA\RGH\ AM22*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\RGH-(23) z:\DATA\RGH\ am22*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\MGH-(23) z:\DATA\MGH\ AM21*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\MGH-(23) z:\DATA\MGH\ am22*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\MUNIM-(23) z:\DATA\MUNIM\ AM22*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\MUNIM-(23) z:\DATA\MUNIM\ am23*.D*  ACCMNOTE.D* *.CSH *.BAT *.XLS *.DOC *.TXT *.BLS *.ARJ
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\M-23(23).MKR z:\M-KR\M23\ *.*
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\MAIL(23) z:\RAJ\MAIL\ *.*
*ARJ A -G:��Ƹ x:\RAJ\MKBACKUP\TASK(23) z:\RAJ\MKTASK\ *.*
ARJ A -G:��Ƹ x:\RAJ\MKBACKUP\M-KR(23).MKR z:\M-KR\ *.*
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\J-Ks(23).MKR Z:\ACMJK99\ *.MKR MASTE*.ACM ACMAST.DBF SYSTAREA.ACM SYSTAX1.ACM
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\J-Ks(23).MKR D:\ACCMANJK\ *.MKR MASTE*.ACM ACMAST.DBF SYSTAREA.ACM SYSTAX1.ACM
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\J-Ks(23).MKR X:\ACCMANJK\ *.MKR MASTE*.ACM ACMAST.DBF SYSTAREA.ACM SYSTAX1.ACM
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\J-Ks(23).MKR X:\ACMJK99\ *.MKR MASTE*.ACM ACMAST.DBF SYSTAREA.ACM SYSTAX1.ACM
ARJ A -R -G:��Ƹ x:\RAJ\MKBACKUP\J-Ks(23).MKR Z:\DATA\SHARE\ AMJNCD.DBF
ARJ A -G:��Ƹ x:\RAJ\MKBACKUP\J-Ks(23).MKR z:\RAJ\PROGRAMS\ *.BAT
ARJ M -G:��Ƹ x:\RAJ\MKBACKUP\DATA23.M23 x:\RAJ\MKBACKUP\ d???(23).* B*.* J*.* C*.* SH*.* RGH*.* MGH*.* SONU*.*

pause