version: "3.9"

services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./rr-front:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    image: php:7.4-fpm
    volumes:
      - ./rr-front:/var/www/html

networks:
  default:
    name: my-network
