# define local IPs
acl IP1 localip 172.31.25.55 # private IP1
acl IP2 localip 172.31.25.56 # private IP2
tcp_outgoing_address 172.31.25.55 IP1
tcp_outgoing_address 172.31.25.56 IP2

# allowed destination ports
acl SSL_PORTS port 443
acl SAFE_PORTS port 80          # http
acl SAFE_PORTS port 21          # ftp
acl SAFE_PORTS port 443         # https
acl SAFE_PORTS port 70          # gopher
acl SAFE_PORTS port 210         # wais
acl SAFE_PORTS port 1025-65535  # unregistered ports
acl SAFE_PORTS port 280         # http-mgmt
acl SAFE_PORTS port 488         # gss-http
acl SAFE_PORTS port 591         # filemaker
acl SAFE_PORTS port 777         # multiling http
acl CONNECT method CONNECT

# define access
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow localhost manager
http_access deny manager
http_access deny all

# disable all logging
access_log none
cache_store_log none
cache_log /dev/null

# disable caching
cache deny all

# needed
server_persistent_connections off

# minor anon
via off
forwarded_for off